### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Phizik-PRO** [jahvi/FileUploadAttribute#1]
How to fix the error? After installing the module lost the ability to edit the attributes en masse. When you delete a module, I can not get into catalog.
![d2lqxwmdbe8](https://cloud.githubusercontent.com/assets/15828348/11295036/3d58b010-8f79-11e5-9a98-37a44a763ea2.jpg)
![tpvwguvtw88](https://cloud.githubusercontent.com/assets/15828348/11295040/4235c79e-8f79-11e5-8bbc-925fd96c0630.jpg)

**Comment by jahvi** [comment]
Can you let me know what Magento version are you using?

**Comment by Phizik-PRO** [comment]
first it was 1.9.2.1
Now updated to 1.9.2.2

**Comment by jahvi** [comment]
And it didn't work in any of them or was it working fine in 1.9.2.1?

**Comment by Phizik-PRO** [comment]
Nowhere did not work

**Comment by jahvi** [comment]
Should be fixed now and updated in magento connect

**Comment by Phizik-PRO** [comment]
Error gone! Thank you!

**Comment by jahvi** [comment]
Would you mind writing a short review at:
http://www.magentocommerce.com/magento-connect/file-upload-attribute.html

It'd help a lot, thanks!

On Sat, Nov 21, 2015 at 3:08 PM, Phizik-PRO notifications@github.com
wrote:

> Error gone! Thank you!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jahvi/FileUploadAttribute/issues/1#issuecomment-158650345
> .
> Untracked with Trackbuster https://trackbuster.com/?sig

## 

Ing. Javier Villanueva

**Comment by Phizik-PRO** [comment]
without any problems, thanks for a nice addition to Magento
