### ISSUE TITLE
Great expansion. 

### ISSUE THREAD

**Issue by dean224** [jahvi/FileUploadAttribute#13]
But I don't know how the product page calls the file. Can you help me
Thanks

**Comment by jahvi** [comment]
Thanks, the file should display by default in the "More Information" tab in the product page.

If you have removed this section or want to add this to another area of your page you can just follow what this file does:
https://github.com/jahvi/FileUploadAttribute/blob/master/app/code/community/Jvs/FileAttribute/Helper/Data.php#L27

In the end this is just a regular file attribute and you can get its value using plain old `$product->getData('attribute_name')`
