### ISSUE TITLE
Uploaded files suddenly gone from media/catalog. Is it related with this extension?

### ISSUE THREAD

**Issue by aguswhome** [jahvi/FileUploadAttribute#15]
Hi Jahvi, thanks for the great extension.
I used it to upload product technical sheet for the products.

After a few months, suddenly the files (pdf) gone from media/catalog folder.

I still don't know why. 

Is it related with this extension?

![image](https://user-images.githubusercontent.com/31946942/43175362-da5c27b2-8fe8-11e8-80f7-9ce8f1e8f220.png)

Thanks,
Agus

**Comment by jahvi** [comment]
Hi, thanks for reaching out!

I don't think this is related as there's nothing in the extension that deletes these files, even if you "delete" the file using the checkbox this only "unsets" it from the product but the actual file should still be there in the media folder.
