### ISSUE TITLE
HTML file format extension unable to add

### ISSUE THREAD

**Issue by rajeshkumar-aut** [jahvi/FileUploadAttribute#2]
Hi Jahvi,
As per my requirement I need to upload html file for custom product type, I have used this extension for file upload attribute, but it is not able to save file I have followed the instruction you have given to extend the file format support. 
I have tried to extend file extension support for html format, using public function changeAllowedFileExtensions(Varien_Event_Observer $observer) in Observer.php,
but It is not working to upload the file.
Any suggestion for this..

**Comment by jahvi** [comment]
This was fixed in 1.2.0, please update and try again.
