### ISSUE TITLE
Display attribute value into html template

### ISSUE THREAD

**Issue by JelleGe** [jahvi/FileUploadAttribute#3]
Hi,

I want to echo the input of the file upload attribute into my html template.
This so that I can display the image on the productpage, if is is uploaded.

Normaly I use this code to check if the attribute contains value and echo the value also.

```
<?php if($_product->getData('attribute_title')) : ?>
       <?php echo $this->htmlEscape($_product->getData('attribute_title')); ?>
<?php endif; ?>
```

How can I achieve that with your file upload attribute?

**Comment by jahvi** [comment]
The extension works the same as a regular attribute so you can use the same code, however because it's a file path you might need to do something like:

``` php
<?php if($_product->getData('attribute_title')) : ?>
       <?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $_product->getData('attribute_title'); ?>
<?php endif; ?>
```

And it will output the full URL to the file.
