### ISSUE TITLE
Upload files not saved

### ISSUE THREAD

**Issue by coresh** [jahvi/FileUploadAttribute#4]
Magento v. EE 1.4.2.2

Request with jpg file sent by browser to backend.

Result:
jpg file no saved on hdd

**Comment by jahvi** [comment]
I haven't been able to test it on Magento EE, is there anything in the logs that could help debug this?

**Comment by coresh** [comment]
Unfortunately, no any error logs / exeptions...
According to image uploading:
if you want upgrade/improve your extension, there are
well (ajax-ready) solution, released by
https://github.com/openstream/No-Flash-Image-Uploader

No-Flash-Image-Uploader extension supported only
media_image attribute type.
IMHO: Should be the best/easy way concerning to porting
No-Flash-Image-Uploader extension ajax logic to the FileUploadAttribute extension

**Comment by kruzhalin** [comment]
Warning: It is not yet possible to assign complex types to properties in /lib/Varien/Simplexml/Element.php on line 485

**Comment by jahvi** [comment]
Can confirm, I'll fix it on the next release

**Comment by jahvi** [comment]
Fixed with bb06298
