### ISSUE TITLE
Use attribute output helper instead of rewrite

### ISSUE THREAD

**Issue by DevertNet** [jahvi/FileUploadAttribute#5]
Don't make a rewrite for this:
https://github.com/jahvi/FileUploadAttribute/blob/master/app/code/community/Jvs/FileAttribute/Block/Product/View/Attributes.php

Better use a attribute output helper:
http://www.webguys.de/magento/attribut-werte-vor-der-ausgabe-im-frontend-veraendern/

**Comment by jahvi** [comment]
Thanks, didn't know you could do that I'll include it on the next update
