### ISSUE TITLE
show icon

### ISSUE THREAD

**Issue by Phizik-PRO** [jahvi/FileUploadAttribute#7]
Hi!
please tell me how to make a display of icons on the category page?
![pdf](https://cloud.githubusercontent.com/assets/15828348/16002759/fb8665de-3161-11e6-8245-e914e52cb295.jpg)
html and CSS, I do himself. Prompt how to display an icon

**Comment by jahvi** [comment]
It's a normal attribute so you can get it the same way you'd get any other attribute, eg:

``` php
$attributeValue = $_product->getResource()->getAttribute('your_attribute_code')->getFrontend()->getValue($_product);
```

Then `$attributeValue` would be the path to the image, you could then do:

``` php
echo Mage::getBaseUrl('media') . 'catalog/product' . $attributeValue;
```

To get the full URL to the image.

**Comment by Phizik-PRO** [comment]
Does not work. Such a method displays the value of the standard Magento attribute. FileUpload-аttribute does not show
